### ISSUE TITLE
Migrar do Jekyll para o Honkit

### ISSUE THREAD

**Issue by allythy** [badtuxx/DescomplicandoDocker#17]
**Motivos para migrar:**
 - Possibilidade de exporta do conteúdo do site para pdf, epub, mobi muito fácil.
 - Fazer a tradução para outras línguas. 
 -  Tema muito agradável. Com a possibilidade de alterar o tamanho da fonte, com ou sem serif e cores de fundo(white, sepia, night).
 - Campos de busca.

**Compatibilidades:** 
 - Vai manter as escrita dos arquivos em markdown.
 - O deploy pode ser feito no GitHub pages ou Netlify.

Link do Pull Request onde comecei a fazer fazer migração: #16

**Comment by badtuxx** [comment]
Ficou sensacional manoooo! <3 <3

**Comment by badtuxx** [comment]
https://badtuxx.github.io/DescomplicandoDocker/

Está dando ruim para acessar o conteúdo, @allythy!

**Comment by allythy** [comment]
> https://badtuxx.github.io/DescomplicandoDocker/
> 
> Está dando ruim para acessar o conteúdo, @allythy!

Certo, tem que configurar o GitHub Action para faze o Deploy. Vou ajeitar o arquivo e mando um PR

**Comment by badtuxx** [comment]
Deployado e já em execução! Ficou foda! <3 
Muito obrigado pelo trampo sensacional!

**Comment by badtuxx** [comment]
@allythy bora fazer o mesmo lá no DescomplicandoKubernetes? <3
https://github.com/badtuxx/DescomplicandoKubernetes/issues/146

**Comment by allythy** [comment]
> @allythy bora fazer o mesmo lá no DescomplicandoKubernetes? <3
> [badtuxx/DescomplicandoKubernetes#146](https://github.com/badtuxx/DescomplicandoKubernetes/issues/146)

Vamos sim, vou começar a migração dele também :) @badtuxx
